image:
  repository: stanley17/devops-project
  tag: 7caa00a
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscale:
  enabled: false
httpRoute:
  enabled: false